MAIN_COLOUR = "#EF6C9A"

MAIN_FRAME_COLOR = "#910033"
MAIN_COLOUR_LABEL_BG = "orange"
MAIN_COLOUR_LABEL_TEXT = "white"

CANVAS_COLOUR = "white"
LINE_COLOUR = "black"
RESULT_COLOR = "red"
CLIPPER_COLOR = "blue"

COLUMNS = 26

WINDOW_WIDTH = 1540
WINDOW_HEIGHT = 800

DATA_SITUATION = 1/4
BORDERS_SPACE = 10

DATA_FRAME_WIGHT = WINDOW_WIDTH * DATA_SITUATION - BORDERS_SPACE
DATA_FRAME_HEIGHT = WINDOW_HEIGHT - 2 * BORDERS_SPACE

CANVAS_SITUATION = 1 - DATA_SITUATION
CANVAS_WIDTH = WINDOW_WIDTH * CANVAS_SITUATION - 2 * BORDERS_SPACE
CANVAS_HEIGHT = WINDOW_HEIGHT - 2 * BORDERS_SPACE